version: "3"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}

services:
### Nginx Server ########################################
    nginx:
      build:
        context: ./nginx
      depends_on:
        - php-fpm
      volumes:
        - ${SPOOL_POSTFIX}:/var/spool/postfix
        - ${NGINX_APP_SRC}:${NGINX_APP_DST}
        - ${NGINX_LOGS}:/var/log/nginx/
        - ${NGINX_CONF}:/etc/nginx/nginx.conf
        - ${NGINX_VHOST80_CONF}:/etc/nginx/conf.d/default.conf
      ports:
       - "${NGINX_HOST_HTTP_PORT}:80"
       - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - frontend
      restart: always

### Php-fpm ########################################
    php-fpm:
      build:
        context: ./php-fpm
      volumes:
        - ${NGINX_APP_SRC}:${NGINX_APP_DST}
        - ${PHP_FPM_WWW_CONF}:/usr/local/etc/php-fpm.d/www.conf
        - ${PHP_INI}:/usr/local/etc/php/php.ini
        - ${PHP_XDEBUG_INI}:/usr/local/etc/php/conf.d/20-xdebug.ini
      networks:
        - frontend
      restart: always

### MariaDB ################################################
    mariadb:
      build:
        context: ./mariadb
        args:
          - SYSTEM_TIMEZONE=${SYSTEM_TIMEZONE}
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      volumes:
        - ${MARIADB_DATA}:/var/lib/mariadb/
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      networks:
        - frontend
      restart: always

### Redis Server ########################################
    redis:
      build:
        context: ./redis
      volumes:
        - ${NGINX_LOGS}:/var/log/nginx/
        - ${NGINX_CONF}:/etc/nginx/nginx.conf
      ports:
       - "${REDIS_PORT}:6379"
      networks:
        - frontend
      restart: always
